server:
  port: 8080
  servlet:
    context-path: /bootcamp
spring.main.allow-circular-references: true


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456

  jpa:
    #open-in-view: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para bootcamp DIO - Santander / Iniciacao Cientifica UFRPE
